version: 1.0.6
services:
  SO:
    image: docker.io/library/ubuntu
    container_name: ubuntu_programacion22
    command: sleep infinity
    tty: true
  DB:
    image: docker.io/library/postgres
    container_name: postgres_programacion22
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - '5433:5432'
